### ISSUE TITLE
similarity transformation for 3d points?

### ISSUE THREAD

**Issue by iperov** [axelpale/nudged-py#4]
could you please provide a similar function for 3D points?

**Comment by axelpale** [comment]
I appreciate the request and I have dreamed about such addition. Still, it is like asking me to do a master's thesis amount of work for free (that is what this 2D estimator take). If you have $100k lying around for this I might consider taking on the challenge. In addition, finding the optimal 3D transformation is significantly harder than 2D, especially if it involves rotation because a linear time solution might even not exist.

If you really need such feature asap, are ready to put some work into it, and superb computational efficiency is not required, I recommend you to look for math toolkits that solve _point set registration problem_ or _Procrustes superimposition_ or _similarity matrix estimation_ for general N-dimensional points. Maybe special tools also already exist for 3D point sets. If you find any, I would be interested to know about them too.

On the other hand, if you want to hack it and an approximate solution is okay, you might be able to apply the current 2D estimation to 3D point sets from multiple directions and somehow combine the results... Just an idea, I have not tried it.

Any way, I will close the issue as the request is likely unfeasible for the time being.

**Comment by iperov** [comment]
I already have umeyama func for estimation of N-d transformation. But SVD is not available on ML frameworks such as onnx, so I thought you had a quick solution for 3D.

**Comment by axelpale** [comment]
Cool. I believe SVD is quite computationally intensive operation, being one of the original reasons why I did not begin to explore and apply general N-dimensional tools for the relatively simple 2D case.

Just for curiosity, in your use case, how large the rotations can be? It has been a while since I investigated the 3D case but I remember some reasonably quick optimisations existed when the angle was small, say, less than 45 degrees.

I am glad to hear the Kabsch-Umeyama algorithm exists. Namely, the main problem with 3D estimation is the rotation because instead of single axis of rotation we suddenly have three axes. With the three axes, gimbal lock becomes a big problem both physically and numerically, leading to the use of quaternions to circumvent the issue. Quaternions, unlike rotation matrices, cannot be solved with linear algebra. Therefore, in any case, either via Umeyama or quaternions, some kind of recursion is needed (like SVD), which tends to require lots of computation.

The translation and scaling estimation is possible to do in linear time (O(n) where n is the number of points) for 3D point sets. That is somewhat easy. I might implement quick estimators for those simple cases at some point in future.

**Comment by iperov** [comment]
Thanks for explanation

**Comment by iperov** [comment]
@axelpale 

can you give me some advice

I am using umeyama to estimate 3D transform from 3d face points to straight looking base face 3d points in order to align the face

https://github.com/axelpale/nudged-py/assets/8076202/9366bf23-42d7-4351-81a9-219426fd0436

but on large rotations > 80 degrees the scale is increasing.

**Comment by iperov** [comment]
(nevermind)
